version: '3.7'

services:
  my_aut_id_prod:
    container_name: my_aut_id_prod
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5001:80'